@echo off
REM Batch script to launch MultiProcess.exe multiple times in parallel

REM --- Configuration ---
SET "GLOB_THREAD_COUNT=1"
REM Path to your executable (using relative path from script location)
SET "EXECUTABLE_PATH=%~dp0..\x64\Debug\OpenVDB_Voxel.exe"

REM Directory to store output logs from each instance
SET "MAIN_OUTPUT_DIR=%~dp0Parallel_Run_Logs\BatchJob"

REM Create the main output directory if it doesn't exist
IF NOT EXIST "%MAIN_OUTPUT_DIR%" (
    echo Creating directory for output logs: %MAIN_OUTPUT_DIR%
    MKDIR "%MAIN_OUTPUT_DIR%"
)
REM --- End Configuration ---

REM --- Check if Executable Exists ---
IF NOT EXIST "%EXECUTABLE_PATH%" (
    echo ERROR: Executable not found at "%EXECUTABLE_PATH%"
    echo Please check the EXECUTABLE_PATH in the script.
    pause
    GOTO :EOF
)
echo Executable found: %EXECUTABLE_PATH%
echo.

REM ---Shared Parameters
SET "GLOB_SOURCE_DIR=C:\Local_Data\ABC\ABC_parsed_files\ABC_chunk_00
SET "GLOB_TARGET_DIR=C:\Local_Data\ABC\ABC_Datasets\Segmentation\ABC_Chunk_00\ABC_Data_ks_16_pad_4_bw_5_vs_adaptive_n2"
SET "GLOB_JOB_DIR=C:\Local_Data\ABC\ABC_jobs\job_chunk_00"
SET "JOB_TYPE=--batchJob"

REM --- !!!rember  to change GLOB_THREAD_COUNT!!! --- 
REM --- Instance Blocks Begin --- 

REM --- Instance 1 ---
SET "INSTANCE1_ID=Instance001"
SET "INSTANCE1_APP_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE1_ID%_app_internal.log"
SET "INSTANCE1_SOURCE_DIR=%GLOB_SOURCE_DIR%"
SET "INSTANCE1_TARGET_DIR=%GLOB_TARGET_DIR%"
SET "INSTANCE1_JOB_LOC=%GLOB_JOB_DIR%\%INSTANCE1_ID%.job"
SET "INSTANCE1_STDOUT_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE1_ID%_stdout.txt"
SET "INSTANCE1_STDERR_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE1_ID%_stderr.txt"

echo Launching %INSTANCE1_ID%...
echo   App Log: %INSTANCE1_APP_LOG%
echo   Source:  %INSTANCE1_SOURCE_DIR%
echo   Target:  %INSTANCE1_TARGET_DIR%
echo   JobLoc:  %INSTANCE1_JOB_LOC%
echo   Stdout:  %INSTANCE1_STDOUT_LOG%
echo   Stderr:  %INSTANCE1_STDERR_LOG%
START "%INSTANCE1_ID% Process" /B "%EXECUTABLE_PATH%" "%JOB_TYPE%" "%INSTANCE1_SOURCE_DIR%" "%INSTANCE1_TARGET_DIR%" "%INSTANCE1_JOB_LOC%" "%INSTANCE1_APP_LOG%"> "%INSTANCE1_STDOUT_LOG%" 2> "%INSTANCE1_STDERR_LOG%"
echo.

REM --- Instance 2 ---
SET "INSTANCE2_ID=Instance002"
SET "INSTANCE2_APP_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE2_ID%_app_internal.log"
SET "INSTANCE2_SOURCE_DIR=%GLOB_SOURCE_DIR%"
SET "INSTANCE2_TARGET_DIR=%GLOB_TARGET_DIR%"
SET "INSTANCE2_JOB_LOC=%GLOB_JOB_DIR%\%INSTANCE2_ID%.job"
SET "INSTANCE2_STDOUT_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE2_ID%_stdout.txt"
SET "INSTANCE2_STDERR_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE2_ID%_stderr.txt"

echo Launching %INSTANCE2_ID%...
echo   App Log: %INSTANCE2_APP_LOG%
echo   Source:  %INSTANCE2_SOURCE_DIR%
echo   Target:  %INSTANCE2_TARGET_DIR%
echo   JobLoc:  %INSTANCE2_JOB_LOC%
echo   Stdout:  %INSTANCE2_STDOUT_LOG%
echo   Stderr:  %INSTANCE2_STDERR_LOG%
START "%INSTANCE2_ID% Process" /B "%EXECUTABLE_PATH%" "%JOB_TYPE%" "%INSTANCE2_SOURCE_DIR%" "%INSTANCE2_TARGET_DIR%" "%INSTANCE2_JOB_LOC%" "%INSTANCE2_APP_LOG%"> "%INSTANCE2_STDOUT_LOG%" 2> "%INSTANCE2_STDERR_LOG%"
echo.

REM --- Instance 3 ---
SET "INSTANCE3_ID=Instance003"
SET "INSTANCE3_APP_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE3_ID%_app_internal.log"
SET "INSTANCE3_SOURCE_DIR=%GLOB_SOURCE_DIR%"
SET "INSTANCE3_TARGET_DIR=%GLOB_TARGET_DIR%"
SET "INSTANCE3_JOB_LOC=%GLOB_JOB_DIR%\%INSTANCE3_ID%.job"
SET "INSTANCE3_STDOUT_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE3_ID%_stdout.txt"
SET "INSTANCE3_STDERR_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE3_ID%_stderr.txt"

echo Launching %INSTANCE3_ID%...
echo   App Log: %INSTANCE3_APP_LOG%
echo   Source:  %INSTANCE3_SOURCE_DIR%
echo   Target:  %INSTANCE3_TARGET_DIR%
echo   JobLoc:  %INSTANCE3_JOB_LOC%
echo   Stdout:  %INSTANCE3_STDOUT_LOG%
echo   Stderr:  %INSTANCE3_STDERR_LOG%
START "%INSTANCE3_ID% Process" /B "%EXECUTABLE_PATH%" "%JOB_TYPE%" "%INSTANCE3_SOURCE_DIR%" "%INSTANCE3_TARGET_DIR%" "%INSTANCE3_JOB_LOC%" "%INSTANCE3_APP_LOG%"> "%INSTANCE3_STDOUT_LOG%" 2> "%INSTANCE3_STDERR_LOG%"
echo.

REM --- Instance 4 ---
SET "INSTANCE4_ID=Instance004"
SET "INSTANCE4_APP_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE4_ID%_app_internal.log"
SET "INSTANCE4_SOURCE_DIR=%GLOB_SOURCE_DIR%"
SET "INSTANCE4_TARGET_DIR=%GLOB_TARGET_DIR%"
SET "INSTANCE4_JOB_LOC=%GLOB_JOB_DIR%\%INSTANCE4_ID%.job"
SET "INSTANCE4_STDOUT_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE4_ID%_stdout.txt"
SET "INSTANCE4_STDERR_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE4_ID%_stderr.txt"

echo Launching %INSTANCE4_ID%...
echo   App Log: %INSTANCE4_APP_LOG%
echo   Source:  %INSTANCE4_SOURCE_DIR%
echo   Target:  %INSTANCE4_TARGET_DIR%
echo   JobLoc:  %INSTANCE4_JOB_LOC%
echo   Stdout:  %INSTANCE4_STDOUT_LOG%
echo   Stderr:  %INSTANCE4_STDERR_LOG%
START "%INSTANCE4_ID% Process" /B "%EXECUTABLE_PATH%" "%JOB_TYPE%" "%INSTANCE4_SOURCE_DIR%" "%INSTANCE4_TARGET_DIR%" "%INSTANCE4_JOB_LOC%" "%INSTANCE4_APP_LOG%"> "%INSTANCE4_STDOUT_LOG%" 2> "%INSTANCE4_STDERR_LOG%"
echo.

REM --- Instance 5 ---
SET "INSTANCE5_ID=Instance005"
SET "INSTANCE5_APP_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE5_ID%_app_internal.log"
SET "INSTANCE5_SOURCE_DIR=%GLOB_SOURCE_DIR%"
SET "INSTANCE5_TARGET_DIR=%GLOB_TARGET_DIR%"
SET "INSTANCE5_JOB_LOC=%GLOB_JOB_DIR%\%INSTANCE5_ID%.job"
SET "INSTANCE5_STDOUT_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE5_ID%_stdout.txt"
SET "INSTANCE5_STDERR_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE5_ID%_stderr.txt"

echo Launching %INSTANCE5_ID%...
echo   App Log: %INSTANCE5_APP_LOG%
echo   Source:  %INSTANCE5_SOURCE_DIR%
echo   Target:  %INSTANCE5_TARGET_DIR%
echo   JobLoc:  %INSTANCE5_JOB_LOC%
echo   Stdout:  %INSTANCE5_STDOUT_LOG%
echo   Stderr:  %INSTANCE5_STDERR_LOG%
START "%INSTANCE5_ID% Process" /B "%EXECUTABLE_PATH%" "%JOB_TYPE%" "%INSTANCE5_SOURCE_DIR%" "%INSTANCE5_TARGET_DIR%" "%INSTANCE5_JOB_LOC%" "%INSTANCE5_APP_LOG%"> "%INSTANCE5_STDOUT_LOG%" 2> "%INSTANCE5_STDERR_LOG%"
echo.

REM --- Instance 6 ---
SET "INSTANCE6_ID=Instance006"
SET "INSTANCE6_APP_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE6_ID%_app_internal.log"
SET "INSTANCE6_SOURCE_DIR=%GLOB_SOURCE_DIR%"
SET "INSTANCE6_TARGET_DIR=%GLOB_TARGET_DIR%"
SET "INSTANCE6_JOB_LOC=%GLOB_JOB_DIR%\%INSTANCE6_ID%.job"
SET "INSTANCE6_STDOUT_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE6_ID%_stdout.txt"
SET "INSTANCE6_STDERR_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE6_ID%_stderr.txt"

echo Launching %INSTANCE6_ID%...
echo   App Log: %INSTANCE6_APP_LOG%
echo   Source:  %INSTANCE6_SOURCE_DIR%
echo   Target:  %INSTANCE6_TARGET_DIR%
echo   JobLoc:  %INSTANCE6_JOB_LOC%
echo   Stdout:  %INSTANCE6_STDOUT_LOG%
echo   Stderr:  %INSTANCE6_STDERR_LOG%
START "%INSTANCE6_ID% Process" /B "%EXECUTABLE_PATH%" "%JOB_TYPE%" "%INSTANCE6_SOURCE_DIR%" "%INSTANCE6_TARGET_DIR%" "%INSTANCE6_JOB_LOC%" "%INSTANCE6_APP_LOG%"> "%INSTANCE6_STDOUT_LOG%" 2> "%INSTANCE6_STDERR_LOG%"
echo.

REM --- Instance 7 ---
SET "INSTANCE7_ID=Instance007"
SET "INSTANCE7_APP_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE7_ID%_app_internal.log"
SET "INSTANCE7_SOURCE_DIR=%GLOB_SOURCE_DIR%"
SET "INSTANCE7_TARGET_DIR=%GLOB_TARGET_DIR%"
SET "INSTANCE7_JOB_LOC=%GLOB_JOB_DIR%\%INSTANCE7_ID%.job"
SET "INSTANCE7_STDOUT_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE7_ID%_stdout.txt"
SET "INSTANCE7_STDERR_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE7_ID%_stderr.txt"

echo Launching %INSTANCE7_ID%...
echo   App Log: %INSTANCE7_APP_LOG%
echo   Source:  %INSTANCE7_SOURCE_DIR%
echo   Target:  %INSTANCE7_TARGET_DIR%
echo   JobLoc:  %INSTANCE7_JOB_LOC%
echo   Stdout:  %INSTANCE7_STDOUT_LOG%
echo   Stderr:  %INSTANCE7_STDERR_LOG%
START "%INSTANCE7_ID% Process" /B "%EXECUTABLE_PATH%" "%JOB_TYPE%" "%INSTANCE7_SOURCE_DIR%" "%INSTANCE7_TARGET_DIR%" "%INSTANCE7_JOB_LOC%" "%INSTANCE7_APP_LOG%"> "%INSTANCE7_STDOUT_LOG%" 2> "%INSTANCE7_STDERR_LOG%"
echo.

REM --- Instance 8 ---
SET "INSTANCE8_ID=Instance008"
SET "INSTANCE8_APP_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE8_ID%_app_internal.log"
SET "INSTANCE8_SOURCE_DIR=%GLOB_SOURCE_DIR%"
SET "INSTANCE8_TARGET_DIR=%GLOB_TARGET_DIR%"
SET "INSTANCE8_JOB_LOC=%GLOB_JOB_DIR%\%INSTANCE8_ID%.job"
SET "INSTANCE8_STDOUT_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE8_ID%_stdout.txt"
SET "INSTANCE8_STDERR_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE8_ID%_stderr.txt"

echo Launching %INSTANCE8_ID%...
echo   App Log: %INSTANCE8_APP_LOG%
echo   Source:  %INSTANCE8_SOURCE_DIR%
echo   Target:  %INSTANCE8_TARGET_DIR%
echo   JobLoc:  %INSTANCE8_JOB_LOC%
echo   Stdout:  %INSTANCE8_STDOUT_LOG%
echo   Stderr:  %INSTANCE8_STDERR_LOG%
START "%INSTANCE8_ID% Process" /B "%EXECUTABLE_PATH%" "%JOB_TYPE%" "%INSTANCE8_SOURCE_DIR%" "%INSTANCE8_TARGET_DIR%" "%INSTANCE8_JOB_LOC%" "%INSTANCE8_APP_LOG%"> "%INSTANCE8_STDOUT_LOG%" 2> "%INSTANCE8_STDERR_LOG%"
echo.

REM --- Instance 9 ---
SET "INSTANCE9_ID=Instance009"
SET "INSTANCE9_APP_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE9_ID%_app_internal.log"
SET "INSTANCE9_SOURCE_DIR=%GLOB_SOURCE_DIR%"
SET "INSTANCE9_TARGET_DIR=%GLOB_TARGET_DIR%"
SET "INSTANCE9_JOB_LOC=%GLOB_JOB_DIR%\%INSTANCE9_ID%.job"
SET "INSTANCE9_STDOUT_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE9_ID%_stdout.txt"
SET "INSTANCE9_STDERR_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE9_ID%_stderr.txt"

echo Launching %INSTANCE9_ID%...
echo   App Log: %INSTANCE9_APP_LOG%
echo   Source:  %INSTANCE9_SOURCE_DIR%
echo   Target:  %INSTANCE9_TARGET_DIR%
echo   JobLoc:  %INSTANCE9_JOB_LOC%
echo   Stdout:  %INSTANCE9_STDOUT_LOG%
echo   Stderr:  %INSTANCE9_STDERR_LOG%
START "%INSTANCE9_ID% Process" /B "%EXECUTABLE_PATH%" "%JOB_TYPE%" "%INSTANCE9_SOURCE_DIR%" "%INSTANCE9_TARGET_DIR%" "%INSTANCE9_JOB_LOC%" "%INSTANCE9_APP_LOG%"> "%INSTANCE9_STDOUT_LOG%" 2> "%INSTANCE9_STDERR_LOG%"
echo.

REM --- Instance 10 ---
SET "INSTANCE10_ID=Instance010"
SET "INSTANCE10_APP_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE10_ID%_app_internal.log"
SET "INSTANCE10_SOURCE_DIR=%GLOB_SOURCE_DIR%"
SET "INSTANCE10_TARGET_DIR=%GLOB_TARGET_DIR%"
SET "INSTANCE10_JOB_LOC=%GLOB_JOB_DIR%\%INSTANCE10_ID%.job"
SET "INSTANCE10_STDOUT_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE10_ID%_stdout.txt"
SET "INSTANCE10_STDERR_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE10_ID%_stderr.txt"

echo Launching %INSTANCE10_ID%...
echo   App Log: %INSTANCE10_APP_LOG%
echo   Source:  %INSTANCE10_SOURCE_DIR%
echo   Target:  %INSTANCE10_TARGET_DIR%
echo   JobLoc:  %INSTANCE10_JOB_LOC%
echo   Stdout:  %INSTANCE10_STDOUT_LOG%
echo   Stderr:  %INSTANCE10_STDERR_LOG%
START "%INSTANCE10_ID% Process" /B "%EXECUTABLE_PATH%" "%JOB_TYPE%" "%INSTANCE10_SOURCE_DIR%" "%INSTANCE10_TARGET_DIR%" "%INSTANCE10_JOB_LOC%" "%INSTANCE10_APP_LOG%"> "%INSTANCE10_STDOUT_LOG%" 2> "%INSTANCE10_STDERR_LOG%"
echo.

REM --- Instance 11 ---
SET "INSTANCE11_ID=Instance011"
SET "INSTANCE11_APP_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE11_ID%_app_internal.log"
SET "INSTANCE11_SOURCE_DIR=%GLOB_SOURCE_DIR%"
SET "INSTANCE11_TARGET_DIR=%GLOB_TARGET_DIR%"
SET "INSTANCE11_JOB_LOC=%GLOB_JOB_DIR%\%INSTANCE11_ID%.job"
SET "INSTANCE11_STDOUT_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE11_ID%_stdout.txt"
SET "INSTANCE11_STDERR_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE11_ID%_stderr.txt"

echo Launching %INSTANCE11_ID%...
echo   App Log: %INSTANCE11_APP_LOG%
echo   Source:  %INSTANCE11_SOURCE_DIR%
echo   Target:  %INSTANCE11_TARGET_DIR%
echo   JobLoc:  %INSTANCE11_JOB_LOC%
echo   Stdout:  %INSTANCE11_STDOUT_LOG%
echo   Stderr:  %INSTANCE11_STDERR_LOG%
START "%INSTANCE11_ID% Process" /B "%EXECUTABLE_PATH%" "%JOB_TYPE%" "%INSTANCE11_SOURCE_DIR%" "%INSTANCE11_TARGET_DIR%" "%INSTANCE11_JOB_LOC%" "%INSTANCE11_APP_LOG%"> "%INSTANCE11_STDOUT_LOG%" 2> "%INSTANCE11_STDERR_LOG%"
echo.

REM --- Instance 12 ---
SET "INSTANCE12_ID=Instance012"
SET "INSTANCE12_APP_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE12_ID%_app_internal.log"
SET "INSTANCE12_SOURCE_DIR=%GLOB_SOURCE_DIR%"
SET "INSTANCE12_TARGET_DIR=%GLOB_TARGET_DIR%"
SET "INSTANCE12_JOB_LOC=%GLOB_JOB_DIR%\%INSTANCE12_ID%.job"
SET "INSTANCE12_STDOUT_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE12_ID%_stdout.txt"
SET "INSTANCE12_STDERR_LOG=%MAIN_OUTPUT_DIR%\%INSTANCE12_ID%_stderr.txt"

echo Launching %INSTANCE12_ID%...
echo   App Log: %INSTANCE12_APP_LOG%
echo   Source:  %INSTANCE12_SOURCE_DIR%
echo   Target:  %INSTANCE12_TARGET_DIR%
echo   JobLoc:  %INSTANCE12_JOB_LOC%
echo   Stdout:  %INSTANCE12_STDOUT_LOG%
echo   Stderr:  %INSTANCE12_STDERR_LOG%
START "%INSTANCE12_ID% Process" /B "%EXECUTABLE_PATH%" "%JOB_TYPE%" "%INSTANCE12_SOURCE_DIR%" "%INSTANCE12_TARGET_DIR%" "%INSTANCE12_JOB_LOC%" "%INSTANCE12_APP_LOG%"> "%INSTANCE12_STDOUT_LOG%" 2> "%INSTANCE12_STDERR_LOG%"
echo.

REM --- Instance Blocks END ---

echo All instances have been launched in the background.
echo Check the "%MAIN_OUTPUT_DIR%" directory for individual logs.
echo.
echo Your C++ application instances are now running. This script does not wait for them to complete.
pause